version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: spacetrans
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: change.me
